### ISSUE TITLE
Overview map not loading in UE4.26.1

### ISSUE THREAD

**Issue by walid-chekkouri** [ZacharyDK/UtilityCombatSample#1]
I'm trying to open this sample demo using UE4.26.1 however at launch I get this error message:
![image](https://user-images.githubusercontent.com/11277981/109415049-a7228c00-79b6-11eb-85d6-4131296c946f.png)
Some assets aren't loaded either (like animations).
I'm using UE4.26.1, any idea how to fix this? What engine version should I use instead?

**Comment by walid-chekkouri** [comment]
Nevermind, I used the Marketplace version instead

**Comment by ZacharyDK** [comment]
Hmmm. I'll have to look into it. Could have something to do with git LFS shenanigans. But just using the market place version and rebuilding the binaries as needed is an acceptable temporary fix. Ideally, one should be able to download the github package and load it up.
